const FLAGS: Record<string, string> = {
  MEXICO: '🇲🇽',
  SUDAFRICA: '🇿🇦',
  'COREA DEL SUR': '🇰🇷',
  'REP. CHECA': '🇨🇿',
  CANADA: '🇨🇦',
  'BOSNIA Y HERZEG.': '🇧🇦',
  CATAR: '🇶🇦',
  SUIZA: '🇨🇭',
  BRASIL: '🇧🇷',
  MARRUECOS: '🇲🇦',
  HAITI: '🇭🇹',
  ESCOCIA: '🏴',
  AUSTRALIA: '🇦🇺',
  TURQUIA: '🇹🇷',
  'ESTADOS UNIDOS': '🇺🇸',
  PARAGUAY: '🇵🇾',
  ALEMANIA: '🇩🇪',
  CURAZAO: '🇨🇼',
  'PAISES BAJOS': '🇳🇱',
  JAPON: '🇯🇵',
  'COSTA DE MARFIL': '🇨🇮',
  ECUADOR: '🇪🇨',
  SUECIA: '🇸🇪',
  TUNEZ: '🇹🇳',
  ESPANA: '🇪🇸',
  'CABO VERDE': '🇨🇻',
  BELGICA: '🇧🇪',
  EGIPTO: '🇪🇬',
  'ARABIA SAUDITA': '🇸🇦',
  URUGUAY: '🇺🇾',
  IRAN: '🇮🇷',
  'NUEVA ZELANDA': '🇳🇿',
  FRANCIA: '🇫🇷',
  SENEGAL: '🇸🇳',
  IRAK: '🇮🇶',
  NORUEGA: '🇳🇴',
  ARGENTINA: '🇦🇷',
  ARGELIA: '🇩🇿',
  AUSTRIA: '🇦🇹',
  JORDANIA: '🇯🇴',
  PORTUGAL: '🇵🇹',
  'REP. DEL CONGO': '🇨🇩',
  UZBEKISTAN: '🇺🇿',
  COLOMBIA: '🇨🇴',
  INGLATERRA: '🇬🇧',
  CROACIA: '🇭🇷',
  GHANA: '🇬🇭',
  PANAMA: '🇵🇦',
};

export function flagFor(team: string | null | undefined): string {
  if (!team) return '🏳️';
  return FLAGS[team] ?? '🏳️';
}
