const ISO: Record<string, string> = {
  MEXICO: 'mx',
  SUDAFRICA: 'za',
  'COREA DEL SUR': 'kr',
  'REP. CHECA': 'cz',
  CANADA: 'ca',
  'BOSNIA Y HERZEG.': 'ba',
  CATAR: 'qa',
  SUIZA: 'ch',
  BRASIL: 'br',
  MARRUECOS: 'ma',
  HAITI: 'ht',
  ESCOCIA: 'gb-sct',
  AUSTRALIA: 'au',
  TURQUIA: 'tr',
  'ESTADOS UNIDOS': 'us',
  PARAGUAY: 'py',
  ALEMANIA: 'de',
  CURAZAO: 'cw',
  'PAISES BAJOS': 'nl',
  JAPON: 'jp',
  'COSTA DE MARFIL': 'ci',
  ECUADOR: 'ec',
  SUECIA: 'se',
  TUNEZ: 'tn',
  ESPANA: 'es',
  'CABO VERDE': 'cv',
  BELGICA: 'be',
  EGIPTO: 'eg',
  'ARABIA SAUDITA': 'sa',
  URUGUAY: 'uy',
  IRAN: 'ir',
  'NUEVA ZELANDA': 'nz',
  FRANCIA: 'fr',
  SENEGAL: 'sn',
  IRAK: 'iq',
  NORUEGA: 'no',
  ARGENTINA: 'ar',
  ARGELIA: 'dz',
  AUSTRIA: 'at',
  JORDANIA: 'jo',
  PORTUGAL: 'pt',
  'REP. DEL CONGO': 'cd',
  UZBEKISTAN: 'uz',
  COLOMBIA: 'co',
  INGLATERRA: 'gb-eng',
  CROACIA: 'hr',
  GHANA: 'gh',
  PANAMA: 'pa',
};

export function flagUrl(team: string | null | undefined): string | null {
  if (!team) return null;
  const code = ISO[team];
  return code ? `https://flagcdn.com/24x18/${code}.png` : null;
}
